version: "3.9"
services:
  dev:
    image: pytorch/pytorch:1.12.0-cuda11.3-cudnn8-runtime
    working_dir: /workspace
    volumes:
      - .:/workspace
    environment:
      - HYDRA_FULL_ERROR=1
    shm_size: '32gb'
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]